//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Recruitment.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class recruitmentEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new recruitmentEntities object using the connection string found in the 'recruitmentEntities' section of the application configuration file.
        /// </summary>
        public recruitmentEntities() : base("name=recruitmentEntities", "recruitmentEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new recruitmentEntities object.
        /// </summary>
        public recruitmentEntities(string connectionString) : base(connectionString, "recruitmentEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new recruitmentEntities object.
        /// </summary>
        public recruitmentEntities(EntityConnection connection) : base(connection, "recruitmentEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<candidate> candidates
        {
            get
            {
                if ((_candidates == null))
                {
                    _candidates = base.CreateObjectSet<candidate>("candidates");
                }
                return _candidates;
            }
        }
        private ObjectSet<candidate> _candidates;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the candidates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocandidates(candidate candidate)
        {
            base.AddObject("candidates", candidate);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="recruitmentModel", Name="candidate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class candidate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new candidate object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="sur_name">Initial value of the sur_name property.</param>
        /// <param name="position">Initial value of the position property.</param>
        /// <param name="curriculum">Initial value of the curriculum property.</param>
        /// <param name="created_date">Initial value of the created_date property.</param>
        /// <param name="lastupdated_date">Initial value of the lastupdated_date property.</param>
        /// <param name="is_deleted">Initial value of the is_deleted property.</param>
        public static candidate Createcandidate(global::System.Int32 id, global::System.String name, global::System.String sur_name, global::System.String position, global::System.String curriculum, global::System.DateTime created_date, global::System.DateTime lastupdated_date, global::System.Boolean is_deleted)
        {
            candidate candidate = new candidate();
            candidate.id = id;
            candidate.name = name;
            candidate.sur_name = sur_name;
            candidate.position = position;
            candidate.curriculum = curriculum;
            candidate.created_date = created_date;
            candidate.lastupdated_date = lastupdated_date;
            candidate.is_deleted = is_deleted;
            return candidate;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sur_name
        {
            get
            {
                return _sur_name;
            }
            set
            {
                Onsur_nameChanging(value);
                ReportPropertyChanging("sur_name");
                _sur_name = StructuralObject.SetValidValue(value, false, "sur_name");
                ReportPropertyChanged("sur_name");
                Onsur_nameChanged();
            }
        }
        private global::System.String _sur_name;
        partial void Onsur_nameChanging(global::System.String value);
        partial void Onsur_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String position
        {
            get
            {
                return _position;
            }
            set
            {
                OnpositionChanging(value);
                ReportPropertyChanging("position");
                _position = StructuralObject.SetValidValue(value, false, "position");
                ReportPropertyChanged("position");
                OnpositionChanged();
            }
        }
        private global::System.String _position;
        partial void OnpositionChanging(global::System.String value);
        partial void OnpositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String curriculum
        {
            get
            {
                return _curriculum;
            }
            set
            {
                OncurriculumChanging(value);
                ReportPropertyChanging("curriculum");
                _curriculum = StructuralObject.SetValidValue(value, false, "curriculum");
                ReportPropertyChanged("curriculum");
                OncurriculumChanged();
            }
        }
        private global::System.String _curriculum;
        partial void OncurriculumChanging(global::System.String value);
        partial void OncurriculumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created_date
        {
            get
            {
                return _created_date;
            }
            set
            {
                Oncreated_dateChanging(value);
                ReportPropertyChanging("created_date");
                _created_date = StructuralObject.SetValidValue(value, "created_date");
                ReportPropertyChanged("created_date");
                Oncreated_dateChanged();
            }
        }
        private global::System.DateTime _created_date;
        partial void Oncreated_dateChanging(global::System.DateTime value);
        partial void Oncreated_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime lastupdated_date
        {
            get
            {
                return _lastupdated_date;
            }
            set
            {
                Onlastupdated_dateChanging(value);
                ReportPropertyChanging("lastupdated_date");
                _lastupdated_date = StructuralObject.SetValidValue(value, "lastupdated_date");
                ReportPropertyChanged("lastupdated_date");
                Onlastupdated_dateChanged();
            }
        }
        private global::System.DateTime _lastupdated_date;
        partial void Onlastupdated_dateChanging(global::System.DateTime value);
        partial void Onlastupdated_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean is_deleted
        {
            get
            {
                return _is_deleted;
            }
            set
            {
                Onis_deletedChanging(value);
                ReportPropertyChanging("is_deleted");
                _is_deleted = StructuralObject.SetValidValue(value, "is_deleted");
                ReportPropertyChanged("is_deleted");
                Onis_deletedChanged();
            }
        }
        private global::System.Boolean _is_deleted;
        partial void Onis_deletedChanging(global::System.Boolean value);
        partial void Onis_deletedChanged();

        #endregion

    }

    #endregion

}
